online-chat-system:
  datasource:
    host: 8.134.206.148
    port: 3306
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: online_chat_system

  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
    region: