online-chat-system:
  datasource:
    host: localhost
    port: 3306
    username: root
    password: CHEN003325
    driver-class-name: com.mysql.cj.jdbc.Driver
    database: online_chat_system

  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
    region: