server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${online-chat-system.datasource.host}:${online-chat-system.datasource.port}/${online-chat-system.datasource.database}?allowPublicKeyRetrieval=true
    username: ${online-chat-system.datasource.username}
    password: ${online-chat-system.datasource.password}
    driver-class-name: ${online-chat-system.datasource.driver-class-name}



mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.gdpu: debug
    org.springdoc: debug
    com.github.xiaoymin.knife4j: debug


knife4j:
  enable: true
  openapi:
    title: 在线聊天系统接口文档
    description: "在线聊天系统接口文档"
    email: 3072740995@qq.com
    concat: MoRan
    url:
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.gdpu.controller

online-chat-system:
  alioss:
    endpoint: ${online-chat-system.alioss.endpoint}
    access-key-id: ${online-chat-system.alioss.access-key-id}
    access-key-secret: ${online-chat-system.alioss.access-key-secret}
    bucket-name: ${online-chat-system.alioss.bucket-name}
    region: ${online-chat-system.alioss.region}


